"""added dms id column to friends table

Revision ID: 3db608281b6d
Revises: 1ecab0804c22
Create Date: 2024-05-31 21:08:45.524819

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3db608281b6d"
down_revision: Union[str, None] = "1ecab0804c22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "friends", "dms", ["dm_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "friends", type_="foreignkey")
    # ### end Alembic commands ###
