"""changed created_date to date

Revision ID: c209f8f4277c
Revises: ba16aa3944f1
Create Date: 2024-06-08 12:22:30.316355

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c209f8f4277c"
down_revision: Union[str, None] = "ba16aa3944f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dm_messages", "created_date", new_column_name="date")
    op.alter_column("server_messages", "created_date", new_column_name="date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dm_messages", "date", new_column_name="created_date")
    op.alter_column("server_messages", "date", new_column_name="created_date")
